[Defaults]
output_dir = "out"
workflow = "bagger/config/default_workflow.json"
dart_command = "dart-runner"
overwrite = false

[Logging]
log_dir = "logs"
logfile_prefix = "ReBACH-Bagger"

[Wasabi]
name = "***override***"
host = "***override***"
bucket = "***override***"
host_bucket = "***override***"
access_key = "***override***"
secret_key = "***override***"

[Metadata]
# tag-file.Tag-Name = "tag_source"
# https://github.com/UAL-RE/ReBACH/blob/12-merge-rebach-bagger/bagger/README.md#metadata

bag-info.DOI = "doi"
bag-info.License = "license.name"
bag-info.Published-Date = "published_date"
aptrust-info.Title = "title"
aptrust-info.Description = { tag_source = "description", strip_html = true }